In [2]:
import numpy as np
import sympy as smp
from sympy.vector import *
import matplotlib.pyplot as plt
from scipy.integrate import quad, quad_vec

In [3]:
x, y, z, u1, u2, u3, v1, v2, v3, t = smp.symbols('x y z u_1 u_2 u_3 v_1 v_2 v_3 t')

<h4>Vectors and Geometry</h4>

In [11]:
a = np.array([1, 2, 3])
b = np.array([7, 8, 9])
u = smp.Matrix([u1, u2, u3])
v = smp.Matrix([v1, v2, v3])

In [13]:
u.subs(u1, 4)

Matrix([
[  4],
[u_2],
[u_3]])

Addition and multiplication

In [14]:
2*a+b

array([ 9, 12, 15])

In [15]:
2*u+v

Matrix([
[2*u_1 + v_1],
[2*u_2 + v_2],
[2*u_3 + v_3]])

Dot products

In [23]:
np.dot(a, b)

50

In [24]:
u.dot(v)

u_1*v_1 + u_2*v_2 + u_3*v_3

Cross products

In [26]:
np.cross(a, b)

array([-6, 12, -6])

In [25]:
u.cross(v)

Matrix([
[ u_2*v_3 - u_3*v_2],
[-u_1*v_3 + u_3*v_1],
[ u_1*v_2 - u_2*v_1]])

Length of vector

In [27]:
np.linalg.norm(a)

3.7416573867739413

In [28]:
u.norm()

sqrt(Abs(u_1)**2 + Abs(u_2)**2 + Abs(u_3)**2)

Vector projection

In [30]:
proj_b_a = np.dot(a,b)/np.linalg.norm(b)**2 * b
proj_b_a

array([1.80412371, 2.06185567, 2.31958763])

In [34]:
proj_v_u = u.dot(v)/v.norm()**2 * v
proj_v_u

Matrix([
[v_1*(u_1*v_1 + u_2*v_2 + u_3*v_3)/(Abs(v_1)**2 + Abs(v_2)**2 + Abs(v_3)**2)],
[v_2*(u_1*v_1 + u_2*v_2 + u_3*v_3)/(Abs(v_1)**2 + Abs(v_2)**2 + Abs(v_3)**2)],
[v_3*(u_1*v_1 + u_2*v_2 + u_3*v_3)/(Abs(v_1)**2 + Abs(v_2)**2 + Abs(v_3)**2)]])

Lines/Planes in Space

In [50]:
r0 = smp.Matrix([1, 1, 1])
v = smp.Matrix([1, 3, -1])
r = r0 + t*v
r

Matrix([
[  t + 1],
[3*t + 1],
[  1 - t]])

In [39]:
P0 = smp.Matrix([4, 4, 8])
r = smp.Matrix([x,y,z])
n = smp.Matrix([1,1,1])
n.dot(P0-r)

-x - y - z + 16

<p style="font-size: 12px;"><strong>Examples</strong> Find vecotor paralled to the line of intersection of the two planes 3x - 6y - 2z and 2x + y -2z = 5.</p>

In [51]:
n1 = np.array([-3, 6, 2])
n2 = np.array([-2, -1, 2])
ans = np.cross(n1, n2)
ans


array([14,  2, 15])

<h4>Vector Calculus</h4>

Vector Derivatives

In [57]:
r = smp.Matrix([3*t, smp.sin(t), t**2])
smp.Derivative(r)

Derivative(Matrix([
[   3*t],
[sin(t)],
[  t**2]]), t)

In [58]:
smp.Derivative(r).doit()

Matrix([
[     3],
[cos(t)],
[   2*t]])

In [64]:
h = smp.Derivative(400*t-5*t**2)
h.doit()


400 - 10*t